### PR TITLE
resolves #562 by returning the exception of the last preprocessing error

### LINKED ISSUE #562: Cryptic error when all samples fail to preprocess
If all samples fail to preprocess when running model.predict() or model.train() the user will see "IndexError: Tried all samples, none were safe" but won't see the underlying errors because they are caught by SafeDatasets. Maybe we should have a flag for raising rather than catching preprocessing errors, or some other way to see the underlying errors when samples fail to preprocess.

### PR DESCRIPTION
**Pull request by louisfh**
This commit alters the SafeDataset class. It does so by returning the last sample's exception if all of the samples in a dataset are unsafe.
@sammlapp what do you think about this solution?
It changes the implementation of the SafeDataset class - which I was hesitant to do. However it seems cleaner than adding another argument to a function like `model.train`. The default behavior now is that if every sample is unsafe it will show the last exception raised. However I am not sure the exception raised is actually much more informative than the existing exception!

You can see the behavior by checking out this branch and trying e.g.:

```
import opensoundscape as oss
import pandas as pd
audio_dataset = pd.DataFrame(zip([1]*30, [0]*30), index= [f"/home/notafile{i}.wav" for i in range(30)], columns=["present", "absent"])
model = oss.torch.models.cnn.CNN('resnet18', classes = ["present", "absent"], sample_duration=3)
model.train(audio_dataset)
```

### CODE REVIEW

**Comment by louisfh** [comment]
We should change this. This does address the issue - but after talking about it it seems what would be better is if we have some kind of debugging mode. e.g. we could set `model.debug=True` and make the preprocessor raise every error. This would be done by passing `"unsafe_behavior = "raise"` to SafeDataset.

**Comment by sammlapp** [comment]
I agree that we should rely on the existing ability of SafeDataset's `unsafe_behavior` modes here. Although it adds an argument, I think having model.train() and model.predict() expose the `unsafe_behavior` argument actually makes sense. This is something the user should be able to control in the API. 

(Having `model.debug=False` would be hidden/undocumented in a way that is difficult to discover. )

HOWEVER, I need to think about this more because under the hood, predict still uses `substitute` then goes back and replaces failed samples with NaN (#280 requests that this be fixed, but I haven't thought of the right way to do it)

**Comment by louisfh** [comment]
Resolved with a new branch #646

**Comment by louisfh** [comment]
Sorry for new branch - ended up doing it because of pytest/poetry issues. I can push the changes to here if preferred.

**Pull request closed without merging**
